name: linters

on: [push, pull_request]

jobs:

  Black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2
      - uses: psf/black@20.8b1
        with:
          args: ". --check"

  Pycodestyle:
    name: Lint Pycodestyle
    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/yashaka/selene/dev-deps:2.0.0a36
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.7'
      - name: Pycodestyle
        run: |
          pycodestyle $(pwd) --ignore=E501,W503,E402,E731 --exclude=.venv,tests_from_past

  Pycodestyle-full-report:
    name: Lint Pycodestyle Full Report
    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/yashaka/selene/dev-deps:2.0.0a36
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.7'
      - name: Pycodestyle Full Report
        run: |
          pycodestyle $(pwd) --ignore=E501,W503 --exclude=.venv,tests_from_past
        continue-on-error: true

  Pylint:
    name: Lint Pylint
    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/yashaka/selene/dev-deps:2.0.0a36
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.7'
      - name: Pylint
        run: |
          touch __init__.py
          pylint $(pwd) --rcfile=.pylintrc --disable="$(cat .pylint-disabled-rules)" --ignore-patterns=.venv,tests_from_past
          rm __init__.py

  Pylint-full-report:
    name: Lint Pylint Full Report
    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/yashaka/selene/dev-deps:2.0.0a36
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.7'
      - name: Pylint Full Report
        run: |
          touch __init__.py
          pylint $(pwd) --rcfile=.pylintrc --disable="" --ignore-patterns=.venv,tests_from_past --exit-zero
          rm __init__.py
