name: tests

on: [push, pull_request]

jobs:

  test:
    name: Test selene
    runs-on: ubuntu-20.04
    env:
      DISPLAY: ":99"
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            +(selene|tests)/**/*.py
          FILES: |
            poetry.lock
            tests.yml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
        if: env.GIT_DIFF

      # can be packaged as Docker-image
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
        if: env.GIT_DIFF

      # can be packaged as Docker-image
      - name: Install Firefox & Chrome & xvfb
        run: |
          sudo apt-get update
          sudo apt-get install firefox
          sudo apt-get install google-chrome-stable
          sudo apt-get install xvfb
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        if: env.GIT_DIFF

      - name: Test selene with pytest
        run: |
          pip3 install pytest-repeat
          poetry run pytest --tb=short tests/integration/element__type_test.py::test_type_waits_for_no_overlay --headless=True --count=2000
        if: env.GIT_DIFF

#      # can be improved by flags/options
#      - name: Code Coverage
#        uses: codecov/codecov-action@v2
#        with:
#          file: ./coverage.xml # optional
#          name: selene-codecov # optional
#          fail_ci_if_error: true # optional (default = false)
#          verbose: true
#        if: env.GIT_DIFF

#      # can be organized better
#      - name: Upload pytest test results
#        uses: actions/upload-artifact@v2
#        with:
#          name: Code coverage
#          path: |
#            Artifacts
#            coverage.xml
#        if: env.GIT_DIFF
